const bookingFrom = page$('#booking-from');
const bookingTo = page$('#booking-to');
const bookingDate = page$('#booking-date');
pageOptions(bookingFrom, pageLocations());
pageOptions(bookingTo, pageLocations(), 'Select destination');
bookingDate.value = today();
const bookingQuery = new URLSearchParams(location.search);
if (bookingQuery.get('from')) bookingFrom.value = bookingQuery.get('from');
if (bookingQuery.get('to')) bookingTo.value = bookingQuery.get('to');
if (bookingQuery.get('date')) bookingDate.value = bookingQuery.get('date');
let chosenTrip = null;
function storedTrips() { return pageStore.get('trips', []).filter(trip => trip.status !== 'Cancelled' && trip.status !== 'Completed'); }
function seatsForTrip(trip) { const taken = pageStore.get('bookings', []).filter(item => item.tripId === trip.id && item.status !== 'Cancelled').map(item => item.seat); return Array.from({length:Number(trip.capacity || 0)}, (_, index) => `S${index + 1}`).filter(seat => !taken.includes(seat)); }
function showBookingModal(trip) { chosenTrip = trip; const taken = pageStore.get('bookings', []).filter(item => item.tripId === trip.id && item.status !== 'Cancelled').map(item => item.seat); const capacity = Number(trip.capacity || 0); page$('#booking-modal-content').innerHTML = `<p class="eyebrow">SELECT A SEAT</p><h2>${trip.from} → ${trip.to}</h2><p class="modal-intro">${dateLabel(trip.date)} · ${trip.departure || 'N/A'} · ${trip.bus || 'Bus unassigned'} · ${pageMoney(trip.fare)}</p><div class="seat-map">${Array.from({length:capacity}, (_,index) => { const seat=`S${index+1}`; return `<button class="seat ${taken.includes(seat) ? 'occupied' : ''}" ${taken.includes(seat) ? 'disabled' : ''} data-seat="${seat}">${seat}</button>`; }).join('')}</div><p id="seat-message" class="form-message error"></p><button class="button" id="booking-pay" disabled>Continue to demo payment <span>→</span></button>`; page$('#booking-modal').classList.remove('hidden'); page$$('.seat:not(.occupied)').forEach(seat => seat.addEventListener('click', () => { page$$('.seat').forEach(item => item.classList.remove('selected')); seat.classList.add('selected'); page$('#booking-pay').disabled = false; page$('#booking-pay').onclick = () => completeBooking(seat.dataset.seat); })); }
function completeBooking(seat) { const user = currentUser(); if (!user) { location.href = 'login.html'; return; } const reference = uid('BKG'); const booking = {id:reference, reference, tripId:chosenTrip.id, passengerId:user.id, passenger:user.name, from:chosenTrip.from, to:chosenTrip.to, date:chosenTrip.date, departure:chosenTrip.departure, bus:chosenTrip.bus, seat, fare:Number(chosenTrip.fare || 0), status:'Pending Payment'}; const bookings = pageStore.get('bookings', []); pageStore.set('bookings', [booking, ...bookings]); pageStore.set('payments', [{id:uid('PAY'), bookingId:booking.id, amount:booking.fare, status:'Pending', createdAt:new Date().toISOString()}, ...pageStore.get('payments', [])]); location.href = `payment.html?booking=${encodeURIComponent(booking.id)}`; }
page$('#booking-search').addEventListener('submit', event => { event.preventDefault(); const from=bookingFrom.value, to=bookingTo.value, date=bookingDate.value; page$('#booking-error').textContent=''; if (!from || !to || !date) { page$('#booking-error').textContent='Select an origin, destination, and date.'; return; } if (from === to) { page$('#booking-error').textContent='Please select a different destination.'; return; } const found=storedTrips().filter(trip=>trip.from===from && trip.to===to && (!trip.date || trip.date===date)); page$('#booking-results').innerHTML=found.length ? found.map((trip,index)=>`<article class="trip-card"><div class="trip-route">${trip.from}<span>→</span>${trip.to}<small>${dateLabel(trip.date || date)} · ${trip.departure || 'N/A'}</small></div><div><small>Seats available</small><strong>${seatsForTrip(trip).length}</strong></div><div><strong>${pageMoney(trip.fare)}</strong><small>${trip.bus || 'Bus unassigned'}</small></div><button type="button" class="button button-small" data-trip="${index}">Select <span>→</span></button></article>`).join('') : '<div class="empty-state">No trips available for this route and date. An administrator must create a trip first.</div>'; page$$('[data-trip]').forEach(button=>button.addEventListener('click',()=>showBookingModal({...found[Number(button.dataset.trip)], date}))); });
page$('#booking-close').addEventListener('click',()=>page$('#booking-modal').classList.add('hidden'));
*** End Patch