const passenger = requireRole('passenger');
if (passenger) {
  const bookings = pageStore.get('bookings', []).filter(item => item.passengerId === passenger.id);
  const notifications = pageStore.get('notifications', []).filter(item => !item.userId || item.userId === passenger.id);
  page$('#passenger-name').textContent = `Welcome, ${passenger.name}.`;
  const upcoming = bookings.find(item => item.status === 'Confirmed' && item.date >= today());
  page$('#upcoming-trip').innerHTML = upcoming ? `<div><span class="status-badge active">Confirmed</span><h3>${upcoming.from} <span>→</span> ${upcoming.to}</h3><p>${dateLabel(upcoming.date)} · ${upcoming.departure || 'N/A'} · ${upcoming.bus || 'Bus unassigned'} · Seat ${upcoming.seat}</p></div><a class="button button-small" href="ticket.html?ref=${encodeURIComponent(upcoming.reference)}">View ticket</a>` : '<div><span class="status-badge scheduled">No upcoming trip</span><h3>Your next journey starts here.</h3><p>Search an Enugu route to create your first booking.</p></div><a class="button button-small" href="booking.html">Search trips <span>→</span></a>';
  page$('#passenger-stats').innerHTML = [['Upcoming trips', bookings.filter(item => item.status === 'Confirmed' && item.date >= today()).length], ['Total bookings', bookings.length], ['Confirmed tickets', bookings.filter(item => item.status === 'Confirmed').length], ['Cancelled bookings', bookings.filter(item => item.status === 'Cancelled').length]].map(item => `<div class="stat-card"><small>${item[0]}</small><strong>${item[1]}</strong></div>`).join('');
  page$('#passenger-bookings').innerHTML = bookings.length ? `<table class="data-table"><thead><tr><th>Booking</th><th>Route</th><th>Date · seat</th><th>Status</th><th>Action</th></tr></thead><tbody>${bookings.map(item => `<tr><td><strong>${item.reference}</strong></td><td>${item.from} → ${item.to}</td><td>${dateLabel(item.date)} · ${item.seat}</td><td>${statusBadge(item.status)}</td><td>${item.status === 'Confirmed' ? `<button class="text-link" data-cancel="${item.id}">Cancel</button>` : 'N/A'}</td></tr>`).join('')}</tbody></table>` : '<p class="empty-state">No bookings yet.</p>';
  page$('#passenger-notifications').innerHTML = notifications.length ? notifications.map(note => `<div class="notification-row"><i class="notice-dot"></i><span><strong>${note.title}</strong><small>${note.body}</small></span></div>`).join('') : '<p class="empty-state">No notifications yet.</p>';
  page$$('[data-cancel]').forEach(button => button.addEventListener('click', () => { pageStore.set('bookings', pageStore.get('bookings', []).map(item => item.id === button.dataset.cancel ? {...item, status:'Cancelled'} : item)); pageStore.set('payments', pageStore.get('payments', []).map(item => item.bookingId === button.dataset.cancel ? {...item, status:'Cancelled'} : item)); location.reload(); }));
  page$('#logout').addEventListener('click', logout);
}
